### ISSUE TITLE
go version limit message error in go12min.go file

### ISSUE THREAD

**Issue by ke4nec** [harshavardhana/s3www#1]
maybe var _ = ThisProjectRequiresGo112OrHigher

**Comment by harshavardhana** [comment]
Please send a PR @ke4nec

**Comment by harshavardhana** [comment]
Oh wait that is a canary on purpose to avoid compilation on non Go versions its an expected file.

**Comment by ke4nec** [comment]
> 
> 
> Oh wait that is a canary on purpose to avoid compilation on non-Go 1.12 versions its an expected file.

yes, but there is `var _ = ThisProjectRequiresGo1·2OrHigher` in source code, not Go112, why?

**Comment by harshavardhana** [comment]
Because of the `.` character to avoid compilation
