### ISSUE TITLE
Fixed file

### ISSUE THREAD

**Issue by Sipioteo** [harshavardhana/s3www#19]
Add the possibility to call always the same file whatever the url is.
It's useful to starting simple SAP software without getting mess with something like ngins.

Thank you!

**Comment by harshavardhana** [comment]
not sure I fully understand, can you elaborate more with some concrete examples?

**Comment by Sipioteo** [comment]
Yeah so, i got this SAP (Single Application Software). It has only a "index.html" file and nothing else.
The index.html file runs a js script who parse the url and provide the right informations.
For example:
example.com -> example.com/index.html
example.com/home -> example.com/index.html (parsing /home and finding right informations)
example.com/hub -> example.com/index.html (parsing /hub and finding right informations)
example.com/settings -> example.com/index.html (parsing /settings and finding right informations)
and so on

Right now, if i call example.com/home it just reply 404 because obviously that file dosen't exist, it's dynamically generated.

**Comment by Sipioteo** [comment]
The best things is probably:
IF (url has an extension):
     return the file requested
ELSE:
     return index.html
END

**Comment by Sipioteo** [comment]
#20 Here is a really basic, simple solution

**Comment by Sipioteo** [comment]
@harshavardhana  May you publish a new version on docker hub?

**Comment by harshavardhana** [comment]
> @harshavardhana May you publish a new version on docker hub?

Soon @Sipioteo
