### ISSUE TITLE
301 redirection on `/` and `index.html` that removes trailing slash breaks HTML relative paths

### ISSUE THREAD

**Issue by johnchristopher** [harshavardhana/s3www#6]
Hello,

```shell
$ http http://localhost:8080/index.html --print=hH
GET /index.html HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.8

HTTP/1.1 301 Moved Permanently
Content-Length: 0
Date: Thu, 10 Sep 2020 16:17:23 GMT
Location: ./
```
It's okay for the root folder since relative paths have a correct starting point but not for subfolder:

```shell
$ http http://localhost:8080/subfolder/ --print=hH
GET /subfolder/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.8

HTTP/1.1 301 Moved Permanently
Content-Length: 0
Date: Thu, 10 Sep 2020 16:17:34 GMT
Location: ../subfolder
```
Now index.html with a `./css/styles.css` produces a `http://localhost:8080/css/styles.css` instead of `http://localhost:8080/subfolder/css/styles.css`.

Any other URL file paths but index.html are okay:
```shell
$ http http://localhost:8080/subfolder/test.html --print=hH
GET /subfolder/test.html HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.8

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 12649
Content-Type: text/html; charset=utf-8
Date: Thu, 10 Sep 2020 16:22:54 GMT
Last-Modified: Thu, 10 Sep 2020 14:56:57 GMT
```

Is if fixable ?

**Comment by harshavardhana** [comment]
@johnchristopher I don't think this would make sense, you should use absolute paths avoid relative URLs.

**Comment by johnchristopher** [comment]
I have many HTML integrations in subfolders and using relative paths allows me to rename and move them as will. I also prepare some layouts @home on localhost:xxxx and then upload/sync it to minion containers in different subfolders. Relative paths also allows me to simply open the file with a browser rather than using a web server in front of it.

Relative paths is pretty standards when you don't know in advance the name of the host, much less the folders on the web server where your files are hosted.

I just checked with nginx, ecstatic, python simplehttpserver and php built-in server and they all serve subfolders without removing the trailing slash.

**Comment by harshavardhana** [comment]
@johnchristopher this is not what I am doing, it is the implementation in http.FileServer by Go, what I do is a simple filesystem interface to satisfy the expected constraints.

This project scope is not beyond what http.FileServer supports - I would have to close this for now.

**Comment by johnchristopher** [comment]
Ah, I understand now. Thanks for the explanation.
